### ISSUE TITLE
Heartbeats in relay protocol

### ISSUE THREAD

**Issue by djrenren** [chezbob/chezbob#18]
We had an issue today where the kiosk froze up and had to be rebooted, but the relay server did not notice that the clients had disconnected. We could detect this with heartbeats (or maybe some other signal), but we should detect this so that kiosk non-graceful reboots don't require restarting the relay service.

**Comment by khoover** [comment]
The `ws` library has an example at https://www.npmjs.com/package/ws#how-to-detect-and-close-broken-connections

**Comment by djrenren** [comment]
This is a great issue for anyone interesting the more plumbing parts of chezbob. Changes should only be required in:


1. [`relay/relay.js`](https://github.com/chezbob/chezbob/blob/adc8543b48c5a65085e49bcfd5ad9c8fca7d0d90/relay/relay.js) - Issue pings, wait for pongs, if they don't come, close the socket.

2. [`lib/reconnecting-socket/reconnecting-socket.js`](https://github.com/chezbob/chezbob/blob/adc8543b48c5a65085e49bcfd5ad9c8fca7d0d90/lib/reconnecting-socket/reconnecting-socket.js) - On ping, pong.

Since all services use the same relay client implementation (reconnecting-socket) this will solve this problem for all services.

**Comment by djrenren** [comment]
In: https://github.com/chezbob/chezbob/commit/94fcf77be7994e3b88223a573d1e64324f968dc4 I've added heartbeats that allow the server to detect client disconnects. That's half of this issue closed. Arguably this is the more important half, because we're seeing the kiosk go down a lot but bobolith seems fine.

**Comment by djrenren** [comment]
Just gonna close this as the important part is done.
