### ISSUE TITLE
Add timestamp to transactions

### ISSUE THREAD

**Issue by gakiwate** [chezbob/chezbob#19]

**Comment by djrenren** [comment]
Should just be: Add a column for timestamp (note we'll need to either make it nullable or assign a value to existing transactions. Either is fine, just be sure to comment here and in the code what you did)

Ideally we can make it default to `now()`. If that doesn't work, we'll need to update the `inventory` service to put the value there on `purchase`.

**Comment by djrenren** [comment]
Did a quick search. Looks like sqlite is happy to do default datetimes. There's some debate on whether to use `localtime`, `UTC` or `epoch` time. I'm tempted to use epoch time since it has the least likelihood of being misunderstood... Thoughts?
