### ISSUE TITLE
Add history somewhere online

### ISSUE THREAD

**Issue by ppannuto** [chezbob/chezbob#21]
Lots of good history in the slack recently, but that disappear at some point; nice to have the legacy recorded in Bob somewhere.

Purely out of curiosity, is Chez Bob a reference to Chez Betty? I was just visiting UMich and saw they have a grad co-op called Chez Betty in the "Bob and Betty Beyster" Building
14 replies

[Zac Blanco](https://app.slack.com/team/U01666VTJ92)  [4 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649523580945469?thread_ts=1649523348.282919&cid=C0DCAFT35)
There is a page on chez bob history but it does not talk about where the name came from http://cse-gsa.eng.ucsd.edu/grad-student-lounge/chezbob/history
cse-gsa.eng.ucsd.educse-gsa.eng.ucsd.edu
[History of Chez Bob - UCSD CSE Grad Student Wiki](http://cse-gsa.eng.ucsd.edu/grad-student-lounge/chezbob/history)
Wiki for organizing wisdom and activities related to CSE grad students.

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [4 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649523649936159?thread_ts=1649523348.282919&cid=C0DCAFT35)
I'm guessing it's because it was run by a pair of Bobs
:white_check_mark:
1

[Zac Blanco](https://app.slack.com/team/U01666VTJ92)  [4 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649523860359639?thread_ts=1649523348.282919&cid=C0DCAFT35)
That page references the uptime newsletter v2.6 which has a broken link. I found it via some googling: https://cseweb.ucsd.edu//~little/OldSites/CSE_Uptime/v2.6/uptime.html

Unfortunately it doesn't contain any more useful information:
The food cooperative referred to in v.1, n.10 (November 1990) and v.1, n.11 (December 1990) has changed names from CCCP to Chez Bob.
Also sent to the channel

[Pat Pannuto](https://app.slack.com/team/UP1F3H1HP)  [4 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649524156592159?thread_ts=1649523348.282919&cid=C0DCAFT35)
The name “Chez Betty” is an homage to Chez Bob, a similar system at UCSD.
https://chezbetty.store/about
Bob came first :slightly_smiling_face:
[The Benson Store at UW came second, Betty was third]

[Max Hopkins](https://app.slack.com/team/UPXFEGF4K)  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649524661145609?thread_ts=1649523348.282919&cid=C0DCAFT35)
Ah I missed that! Funny that their building is Bob and Betty also

[Pat Pannuto](https://app.slack.com/team/UP1F3H1HP)  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649524879556709?thread_ts=1649523348.282919&cid=C0DCAFT35)
Well, that’s where Chez Betty’s name comes from — it was renamed from CSE by a donation in ~spring 2014ish IIRC, we started Chez Betty summer 2014
Also sent to the channel

[Joe DeBlasio](https://app.slack.com/team/U0DCDAJ5V)  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649527733607079?thread_ts=1649523348.282919&cid=C0DCAFT35)
See also https://web.archive.org/web/20150705012348/http://chezbob.ucsd.edu/chezbob_articles/

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649529628398639?thread_ts=1649523348.282919&cid=C0DCAFT35)
The Benson Store is also named after a grad student who has been long gone. These names just stick around sometimes

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649529685920569?thread_ts=1649523348.282919&cid=C0DCAFT35)
Although within the past few years the undergrad version at UW rebranded from The Coke Closet (from back in the 90s when UW had an exclusive contract with Pepsi, leading to a secret stash for cs undergrads) to Snack Overflow

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649529713767469?thread_ts=1649523348.282919&cid=C0DCAFT35)
It was also no longer literally in a closet

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649529898659949?thread_ts=1649523348.282919&cid=C0DCAFT35)
More Chez Bob history, courtesy of The Discovery Channel https://youtu.be/3qt3Mr6TqEU[](https://www.youtube.com/)
[YouTube](https://www.youtube.com/)YouTube | [Karl Koscher](https://www.youtube.com/user/super5at)
[Chez Bob](https://youtu.be/3qt3Mr6TqEU)[](https://youtu.be/3qt3Mr6TqEU) 

[Emmanuel Thomé](https://app.slack.com/team/U02LLKJCMLN)  [3 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649531100342059?thread_ts=1649523348.282919&cid=C0DCAFT35)
What happened to the soda robot? Is it still WIP?
Also sent to the channel

[David Hutches](https://app.slack.com/team/U3Y5CTPRT)  [2 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649615412057079?thread_ts=1649523348.282919&cid=C0DCAFT35)
For the sake of completeness…
The original Bobs of Chez Bob are Bob Carragher and Rob Bowdidge, but during that era, a core group of grad students associated with the activity were referred to as “The Bobs”. Thus, the Eric Anderson mentioned on the history page was “Eric-Bob”. Indeed, to this day, that core group, many of whom reside in the Bay Area, still refer to themselves as “The Bobs”, as in an email from Eric in which he noted, “I and the other local Bobs went out to dinner the other night...“.

[supersat](https://app.slack.com/team/U2P758BU0):verified:  [2 days ago](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649622522870839?thread_ts=1649523348.282919&cid=C0DCAFT35)
The soda robot was never deployed AFAIK. I solved the elevator problem for the Benson Store at UW (one of the elevators got a REST API written in Python) but the robotics students didn't keep up their end of the bargain :zany_face:

---

Chez Betty was named after Chez Bob, AFAIK

[9:59](https://ucsdcse.slack.com/archives/C0DCAFT35/p1649523593065469)
Some history: https://web.archive.org/web/20150202230712/http://chezbob.ucsd.edu/credits.html

**Comment by djrenren** [comment]
If anyone wants to compile these into HTML form, we can just create a file: `chezbob/web/static/history.html` and then it will be available at https://chezbob.ucsd.edu/history.html

**Comment by gakiwate** [comment]
https://github.com/chezbob/chezbob-legacy/tree/master/www/museum
https://github.com/chezbob/chezbob-legacy/tree/master/www/images

**Comment by alex-bellon** [comment]
Link dump from Slack:

- https://cseweb.ucsd.edu//~tduerig/soda/index.html
- https://www.cnet.com/culture/want-a-soda-youll-need-to-get-fingerprinted/
- https://slashdot.org/story/06/08/01/2124246/ucsd-biometric-vending-machine
- https://scienceblogs.com/purepedantry/2006/08/02/post-35
- https://www.secureidnews.com/news-item/grad-students-in-san-diego-build-biometric-vending-machine/
- https://www.networkworld.com/article/2351552/show-the-vending-machine-your-finger-and-it-ll-give-you-a-soda.html
- https://web.archive.org/web/20050220013616/https://chezbob.ucsd.edu/credits.html
- https://web.archive.org/web/20050220011808/http://chezbob.ucsd.edu/chezbob_articles/

> **savage**
> Here’s a pointer to one of the old UIs that the soda machine used to have:
> https://cseweb.ucsd.edu//~tduerig/soda/index.html
> I have a video that the discovery channel did on the soda machine
> (RIP)
> Also, the original chez bob espresso machine (and Elektra) was actually purchased as part of an enticement to convince Alex Snoeren to come to UCSD instead of CMU and he graciously sited it in Chez Bob.  Similarly, the soda machine and associated computer equipment I purchased as part of a project to make chez bob “cooler”… there was an enormous kerfuffle when I tried to purchase the soda machine (I think it was a Vendo V-21 or something like that) because doing so violated an infinite number of rules apparently… e.g., the real estate office owns the right to site any vending concession, housing and dining owns the right to operate any vending concession, the employee staff union had some claim on profits from vending concessions, there was a fire marshall issue, etc….  We could have fought them all but instead we got Vendo corporation to invoice us for an “Experiential Graduate Student Research Platform”…

> **supersat**
> https://youtu.be/3qt3Mr6TqEU

**Comment by DylanLukes** [comment]
For readability on not-tall-and-narrow kiosk screens something like this on `#history-content` would be nice.

<img width="169" alt="Screenshot 2023-03-14 at 14 05 46" src="https://user-images.githubusercontent.com/250114/225136165-1decafb3-ef6e-4166-aa35-f1fe2669f3a6.png">

Compare:
<img width="1840" alt="Screenshot 2023-03-14 at 14 07 04" src="https://user-images.githubusercontent.com/250114/225136404-373b5f7b-4698-4ca6-9f81-d991e9f20c93.png">

<img width="1840" alt="Screenshot 2023-03-14 at 14 06 59" src="https://user-images.githubusercontent.com/250114/225136387-1e45e4ff-5492-4020-84f0-abbf859282af.png">

**Comment by alex-bellon** [comment]
I think everything listed here is currently on the website thanks to Marcus, so I will close this issue. If people have further history to add, please open a new issue or PR :)
