### ISSUE TITLE
Better language for 'Add Card'

### ISSUE THREAD

**Issue by djrenren** [chezbob/chezbob#26]
Users have been confused about what 'Add Card' means. Specifically, some think the option adds a payment method. We should use more explicit language.

(We should also consider limiting to a single card...)

**Comment by alex-bellon** [comment]
I can work on this!

Could this menu option: 
https://github.com/chezbob/chezbob/blob/713feba4903350d587883c2f4c4d6ecec0205b1a/web/static/internal/apps/pos/mode.js#L531
be reworded to "Add NFC login card"?

And then this one:
https://github.com/chezbob/chezbob/blob/713feba4903350d587883c2f4c4d6ecec0205b1a/web/static/internal/apps/pos/mode.js#L591
could be reworded to "Tap the card you wish to use to log in to your account (this card is not for payment, Chez Bob only accepts cash)."

Definitely open to suggestions on the wording. Additionally, what are the downsides to a person having multiple cards? It seems like it would be handy to be able to login with your UCSD ID or your AirTag (definitely a made up example) based on whichever is easier for you to access at the moment.

**Comment by alex-bellon** [comment]
Closed by #42
