### ISSUE TITLE
Race condition in cash service leads to double deposits

### ISSUE THREAD

**Issue by djrenren** [chezbob/chezbob#5]
## The Problem

In the first two weeks of deployment we've had a single instance of double depositing.
We know this is a bug in the cash service because the cash service issued two distinct deposit requests:

Deposit 1 (anonymized):
```
Mar 23 13:41:48 bobolith env[234425]: {
Mar 23 13:41:48 bobolith env[234425]:   header: {
Mar 23 13:41:48 bobolith env[234425]:     id: '76c11a38-b571-457a-a309-d46d2434ddfc',
Mar 23 13:41:48 bobolith env[234425]:     to: 'pos',
Mar 23 13:41:48 bobolith env[234425]:     type: 'cash_deposit',
Mar 23 13:41:48 bobolith env[234425]:     from: 'cash'
Mar 23 13:41:48 bobolith env[234425]:   },
Mar 23 13:41:48 bobolith env[234425]:   body: { cents: 2000 }
Mar 23 13:41:48 bobolith env[234425]: }
Mar 23 13:41:48 bobolith env[234425]: {
Mar 23 13:41:48 bobolith env[234425]:   header: {
Mar 23 13:41:48 bobolith env[234425]:     id: 'a0c09d5c-2d53-41d3-862c-4598302eb09b',
Mar 23 13:41:48 bobolith env[234425]:     to: 'inventory',
Mar 23 13:41:48 bobolith env[234425]:     type: 'deposit_money',
Mar 23 13:41:48 bobolith env[234425]:     from: 'pos'
Mar 23 13:41:48 bobolith env[234425]:   },
Mar 23 13:41:48 bobolith env[234425]:   body: { user_id: xxx, cents: 2000 }
Mar 23 13:41:48 bobolith env[234425]: }
```

Deposit 2 (anonymized):
```
Mar 23 13:41:39 bobolith env[234425]: {
Mar 23 13:41:39 bobolith env[234425]:   header: {
Mar 23 13:41:39 bobolith env[234425]:     id: '1ace6703-0b40-42ee-b985-2fffd0e8efbc',
Mar 23 13:41:39 bobolith env[234425]:     to: 'pos',
Mar 23 13:41:39 bobolith env[234425]:     type: 'cash_deposit',
Mar 23 13:41:39 bobolith env[234425]:     from: 'cash'
Mar 23 13:41:39 bobolith env[234425]:   },
Mar 23 13:41:39 bobolith env[234425]:   body: { cents: 2000 }
Mar 23 13:41:39 bobolith env[234425]: }
Mar 23 13:41:39 bobolith env[234425]: {
Mar 23 13:41:39 bobolith env[234425]:   header: {
Mar 23 13:41:39 bobolith env[234425]:     id: '5b7f27ee-c155-4c29-a332-1c49e83cc534',
Mar 23 13:41:39 bobolith env[234425]:     to: 'inventory',
Mar 23 13:41:39 bobolith env[234425]:     type: 'deposit_money',
Mar 23 13:41:39 bobolith env[234425]:     from: 'pos'
Mar 23 13:41:39 bobolith env[234425]:   },
Mar 23 13:41:39 bobolith env[234425]:   body: { user_id: xxxx, cents: 2000 }
Mar 23 13:41:39 bobolith env[234425]: }
```

The logs show that the POS appropriately responds by depositing money for both `cash_deposit` requests, but only one should've been issued in the first place.

**Comment by djrenren** [comment]
## Suspected cause:

Here's the code that handles the `READ_NOTE` event from the bill acceptor:

https://github.com/chezbob/chezbob/blob/40fc7c762651d6be02df470eaa6ed8388f934b39/devices/cash.js#L102-L136

This code assumes that exactly 1 contentful (`ev.channel > 0`) `READ_NOTE` will occur when a bill is recognized. (note that non-contentful ones could precede a bill rejection as they just indicate that something unknown is in the slot). It appears that in this instance we received 2 contentful `READ_NOTE` events. 

I believe the issue is that the bill acceptor can queue up multiple contentful `READ_NOTE` events for a single bill insertion. 

## Proposed fix

I believe there are events that the bill acceptor issues on or after bill acceptance that we can use to detect when the processing of a single bill has completed (successfully or unsuccessfully). We will need to ignore all `READ_NOTE` events between the first contentful one, and the acceptor re-entering the ready state.

We'll need to refer to the SSP manual: https://www.innovative-technology.com/product-files/support-tools/ssp-manual.pdf
and/or just log the sequence of events that occur and reverse engineer. Special care should be taken to make sure we handle bill rejection as well as bill acceptance.

**Comment by khoover** [comment]
Sounds like the simplest solution would be to just explicitly model the state machine, and work with that to figure out when things get sent to the main server.

**Comment by djrenren** [comment]
Many of the states of the bill acceptor are uninteresting to us, so I think we want to avoid reflecting its full state machine into states of the cash service. The code as is, is  structured mostly fine. There's just a misunderstanding of the underlying protocol semantics that we need to clean up. So while we need to *understand* the bill acceptors state machine, we shouldn't model it.

**Comment by djrenren** [comment]
Reviewing the docs, it looks like `Credit Note` or `Note Stacked` would be fine for clearing the lock. Considering we acquire the lock on a successful `READ_NOTE` the only possible outcomes should be:

- `Note Stacked`
- `Note Rejected`
- `Time out` (which leads to disable).

**Comment by djrenren** [comment]
I spent about an hour fiddling with the cash machine, inserting delays and trying to replicate the bug as reported, but was unable to. We received another bug where a user received their deposit, but the bill acceptor returned their money. I followed up with the original filer for this bug and it appears that this was the case in their experience as well. So this means the cash service is correctly emitting a single request for a single bill insertion. There is no race condition or misunderstanding of the bill acceptors state machine.

Instead! What we have here is by design but happening too often:

Basically, there's a 3-party communication for cash deposits:
cash -> POS "Hey I wanna deposit money"
POS -> inventory "Hey I wanna deposit money for user X"
inventory -> POS "done"

___
POS-> cash "done"

If the cash -> POS request times out at the line, then the server accepts the money but the cash machine rejects the bill. This was done on purpose to err on the side of giving people free money rather than unfairly taking their money. Due to this being a byzantine generals style problem, we pretty much have to pick our failure mode. I think we've chosen the right failure mode but we're just failing too often.

I'm going to increase the timeout from 1s to 3s and see if we get any more reports. If not, I'll close this issue.

**Comment by khoover** [comment]
I'm not sure this is possible with the way transactions are handled, but we could try to commit a rollback transaction on timeouts after the reject? Saves a bit of time manually fixing balances if it's just the response that got delayed.

**Comment by djrenren** [comment]
How we handle transactions aside, there's the inherent problem of: "Do we wait to deposit until the money accepted" or "do we wait to accept until it's deposited". We currently do the latter because its failure mode is more pro-user. we could do the former but then we have a failure mode where we take money but don't deposit anything.

There is an advantage to the "deposit after accept" scheme, namely that we don't have nested requests:

cash -> pos "I have cash"
pos -> cash "accept it"
pos -> inventory "deposit"
inventory -> pos "done"

But also it's not a big deal to have them so I'm not too worried.

**Comment by khoover** [comment]
I'm not saying change it from "deposit then accept" to "accept then deposit," I'm saying on the error path in the request, at the same time as we reject, also tell the server to revert the transaction that may or may not have gotten through. Can even wait until after the reject is successful to do it, to be sure we're not taking money.

**Comment by djrenren** [comment]
ah, so have the barcode scanner tell the POS to retract the previous transaction? Yeah that's reasonable, because the cash service wouldn't have to wait for a response to the retraction request. It would just sorta notify.

This would work, but would make the POS more complicated. If upping the timeouts solves the problem I'm more inclined to keep things simple. In theory, timeouts should really be indicating an outage, in which case the retraction command not really work anyway.

**Comment by djrenren** [comment]
Update: this is still happening... not sure how to replicate but will try

**Comment by djrenren** [comment]
Update: we now log the "REJECTION_REASON" for all rejected bills, so if this happens we can see why. We just need to catch it in the wild.

**Comment by djrenren** [comment]
Okay! we have our final answer on this one... sorta. The issue is that in the time between the `READ_NOTE` event and our `POLL` command which implicitly means accept, the device encounters the following error: 

```
May 02 18:31:08 kiosk env[24354]:   info: {
May 02 18:31:08 kiosk env[24354]:     code: 10,
May 02 18:31:08 kiosk env[24354]:     name: 'REAR_SENSOR_ERROR',
May 02 18:31:08 kiosk env[24354]:     description: 'An inconsistency in a position sensor detection was seen'
May 02 18:31:08 kiosk env[24354]:   }
```


I believe this may mean the machine needs some recalibration or internal cleaning. For now though, to resolve this bug, we should switch to a "steal money by default model". While this is technically true, the machine has proven far more unreliable than the server, and the stealing money would only occur in the case of a loss of connection between the kiosk and the inventory service. So far we haven't seen this happen, so we should consider such a case to be rare and worthy of manual fixing. I'm sure people will reach out to us if chezbob eats money. The new flow should be:

 1. Bill acceptor emits its first contentful `READ_NOTE` (we now know a valid bill is in the machine)
 2. Send a request: `cash -> pos : deposit_preflight`, if it fails, reject the bill.
 3. If a user is currently signed in, bump the session timeout (IMPORTANT!) and accept the request: `pos -> cash : deposit_preflight_success`
 4. Cash service attempts to accept the bill.
     a: On success: `cash -> pos : deposit` (note, this is not a request, it is just a notification)
     b: On failure `cash -> pos : bill_failure`
 5. POS attaches user data to the deposit and forwards it to `inventory`:  `pos -> inventory : deposit_to_user`
 
 
 There's an alternate design where, rather than routing the final deposit through the POS, we instead respond to `deposit_preflight` with a `user_id` and allow `cash` to deposit money directly. I don't like this design because it moves more smarts into the `cash` service, and after a deposit, the `pos` still needs to be notified, so it's better to let the `pos` just use the request/response model to deposit the cash and receive the user's balance back.
