### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by TanayKarve** [chezbob/chezbob#55]
Will be nice to have docker support to get the development flow up and running without running into too many issues during installation.

**Comment by djrenren** [comment]
My bet is that this ends up significantly more painful to maintain, but I've been wrong before.

Requirements are minimal:

1. A specific version on node
2. tmux

**Comment by TanayKarve** [comment]
Hmm we can add a script that pull the latest updates from upstream. 
Like:
`npm run update #(i.e. git init && git pull https://github.com/chezbob/chezbob)`
And then:
`npm run debug`

**Comment by alex-bellon** [comment]
Merged with #56
