### ISSUE TITLE
Fix 1 cent issue

### ISSUE THREAD

**Issue by alex-bellon** [chezbob/chezbob#67]
We are seeing issues where after giant order restocks from Costco, some items mysteriously are left with a price of 1 cent. 

Ben did some digging and found that for some reason, sometimes when you scan an item, the barcode gets written into the 'quantity' field in the restock tool, so the restock tool thinks that something now has a price of $20 for 304829085028 units (and so the price should be ~1 cent with rounding).

**Comment by c4du** [comment]
Added basic sanity check that prevent form submission if the bulk price or bulk count is unreasonably large (probably caused by scanned barcode incorrectly propagating into the bulk cost field)
